//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAFC24_Teamkits_Editor_WinForms {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAFC24_Teamkits_Editor_WinForms.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   armbandtype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string armbandtype {
            get {
                return ResourceManager.GetString("armbandtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Başarıyla_kaydedildi_ {
            get {
                return ResourceManager.GetString("Başarıyla kaydedildi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   captainarmband benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string captainarmband {
            get {
                return ResourceManager.GetString("captainarmband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chestbadge benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string chestbadge {
            get {
                return ResourceManager.GetString("chestbadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Color_1_ {
            get {
                return ResourceManager.GetString("Color(1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Color_2_ {
            get {
                return ResourceManager.GetString("Color(2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Color_3_ {
            get {
                return ResourceManager.GetString("Color(3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dlc benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string dlc {
            get {
                return ResourceManager.GetString("dlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hasadvertisingkit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hasadvertisingkit {
            get {
                return ResourceManager.GetString("hasadvertisingkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isembargoed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string isembargoed {
            get {
                return ResourceManager.GetString("isembargoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isinheritbasedetailmap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string isinheritbasedetailmap {
            get {
                return ResourceManager.GetString("isinheritbasedetailmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   islocked benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string islocked {
            get {
                return ResourceManager.GetString("islocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseybacknamefontcase benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseybacknamefontcase {
            get {
                return ResourceManager.GetString("jerseybacknamefontcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseybacknameplacementcode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseybacknameplacementcode {
            get {
                return ResourceManager.GetString("jerseybacknameplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseycollargeometrytype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseycollargeometrytype {
            get {
                return ResourceManager.GetString("jerseycollargeometrytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyfit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyfit {
            get {
                return ResourceManager.GetString("jerseyfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyfrontnumberplacementcode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyfrontnumberplacementcode {
            get {
                return ResourceManager.GetString("jerseyfrontnumberplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyleftsleevebadge benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyleftsleevebadge {
            get {
                return ResourceManager.GetString("jerseyleftsleevebadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynamecolorb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynamecolorb {
            get {
                return ResourceManager.GetString("jerseynamecolorb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynamecolorg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynamecolorg {
            get {
                return ResourceManager.GetString("jerseynamecolorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynamecolorr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynamecolorr {
            get {
                return ResourceManager.GetString("jerseynamecolorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynamefonttype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynamefonttype {
            get {
                return ResourceManager.GetString("jerseynamefonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynamelayouttype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynamelayouttype {
            get {
                return ResourceManager.GetString("jerseynamelayouttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorprimb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorprimb {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorprimg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorprimg {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorprimr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorprimr {
            get {
                return ResourceManager.GetString("jerseynumbercolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorsecb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorsecb {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorsecg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorsecg {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorsecr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorsecr {
            get {
                return ResourceManager.GetString("jerseynumbercolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorterb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorterb {
            get {
                return ResourceManager.GetString("jerseynumbercolorterb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorterg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorterg {
            get {
                return ResourceManager.GetString("jerseynumbercolorterg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseynumbercolorterr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseynumbercolorterr {
            get {
                return ResourceManager.GetString("jerseynumbercolorterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyrenderingdetailmaptype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyrenderingdetailmaptype {
            get {
                return ResourceManager.GetString("jerseyrenderingdetailmaptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyrestriction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyrestriction {
            get {
                return ResourceManager.GetString("jerseyrestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyrightsleevebadge benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyrightsleevebadge {
            get {
                return ResourceManager.GetString("jerseyrightsleevebadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jerseyshapestyle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string jerseyshapestyle {
            get {
                return ResourceManager.GetString("jerseyshapestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kit details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kit_details {
            get {
                return ResourceManager.GetString("Kit details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kit name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kit_name {
            get {
                return ResourceManager.GetString("Kit name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kit number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kit_number {
            get {
                return ResourceManager.GetString("Kit number", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lütfen_dosya_seçin {
            get {
                return ResourceManager.GetString("Lütfen dosya seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lütfen_isim_girin {
            get {
                return ResourceManager.GetString("Lütfen isim girin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lütfen_teamkits_dosyası_açın {
            get {
                return ResourceManager.GetString("Lütfen teamkits dosyası açın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   numberfonttype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string numberfonttype {
            get {
                return ResourceManager.GetString("numberfonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   powid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string powid {
            get {
                return ResourceManager.GetString("powid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   renderingmaterialtype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string renderingmaterialtype {
            get {
                return ResourceManager.GetString("renderingmaterialtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shorts number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Shorts_number {
            get {
                return ResourceManager.GetString("Shorts number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorprimb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorprimb {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorprimg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorprimg {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorprimr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorprimr {
            get {
                return ResourceManager.GetString("shortsnumbercolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorsecb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorsecb {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorsecg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorsecg {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorsecr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorsecr {
            get {
                return ResourceManager.GetString("shortsnumbercolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorterb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorterb {
            get {
                return ResourceManager.GetString("shortsnumbercolorterb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorterg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorterg {
            get {
                return ResourceManager.GetString("shortsnumbercolorterg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumbercolorterr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumbercolorterr {
            get {
                return ResourceManager.GetString("shortsnumbercolorterr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumberfonttype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumberfonttype {
            get {
                return ResourceManager.GetString("shortsnumberfonttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsnumberplacementcode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsnumberplacementcode {
            get {
                return ResourceManager.GetString("shortsnumberplacementcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortsrenderingdetailmaptype benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortsrenderingdetailmaptype {
            get {
                return ResourceManager.GetString("shortsrenderingdetailmaptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortstyle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shortstyle {
            get {
                return ResourceManager.GetString("shortstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorprimb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorprimb {
            get {
                return ResourceManager.GetString("teamcolorprimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorprimg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorprimg {
            get {
                return ResourceManager.GetString("teamcolorprimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorprimpercent benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorprimpercent {
            get {
                return ResourceManager.GetString("teamcolorprimpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorprimr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorprimr {
            get {
                return ResourceManager.GetString("teamcolorprimr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorsecb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorsecb {
            get {
                return ResourceManager.GetString("teamcolorsecb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorsecg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorsecg {
            get {
                return ResourceManager.GetString("teamcolorsecg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorsecpercent benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorsecpercent {
            get {
                return ResourceManager.GetString("teamcolorsecpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolorsecr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolorsecr {
            get {
                return ResourceManager.GetString("teamcolorsecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolortertb benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolortertb {
            get {
                return ResourceManager.GetString("teamcolortertb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolortertg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolortertg {
            get {
                return ResourceManager.GetString("teamcolortertg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolortertpercent benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolortertpercent {
            get {
                return ResourceManager.GetString("teamcolortertpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamcolortertr benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamcolortertr {
            get {
                return ResourceManager.GetString("teamcolortertr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamkitid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamkitid {
            get {
                return ResourceManager.GetString("teamkitid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamkittypetechid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamkittypetechid {
            get {
                return ResourceManager.GetString("teamkittypetechid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teamtechid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string teamtechid {
            get {
                return ResourceManager.GetString("teamtechid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   year benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
